### ISSUE TITLE
code for the examples

### ISSUE THREAD

**Issue by astrale-sharp** [Pablo-Gonzalez-Calderon/showybox-package#11]
Hey there! It would be nice if the examples were displayed with code next to it (or at least in the repo)

thanks!

**Comment by Pablo-Gonzalez-Calderon** [comment]
Sure! I've uploaded the example's code in a new folder named 'examples', there all the examples are inside `examples.typ`, with a brief comment describing what example do they belong to.

I hope it helps! 😉

**Comment by astrale-sharp** [comment]
Thank you, absolutely it does!
I'm closing this then
