### ISSUE TITLE
Make boxed title's horizontal position more customizable

### ISSUE THREAD

**Issue by Andrew15-5** [Pablo-Gonzalez-Calderon/showybox-package#14]
In v1.1.0 boxed title has a `boxed-align` which changes horizontal alignment, but it only has 5 fixed positions. A custom position using float (or ratio) should be added where `0` is equal to `start` and `1` is equal to `end`. Related issue: #13 (with some config examples).

**Comment by Pablo-Gonzalez-Calderon** [comment]
It makes sense to me 🧐

This could be a good change to implement with #13 changes. As I said there, I will look at the code for a possible refactorization of ``boxed`` titles drawing.

**Comment by Pablo-Gonzalez-Calderon** [comment]
Update:

As in #13 was mentioned, an `offset`option is intended to be added. So, the issue with custom position can be considered solved, and its implementation discussion moved to #13 🎉.
