### ISSUE TITLE
showybox:2.0.2 - Interaction with page margin

### ISSUE THREAD

**Issue by maucejo** [Pablo-Gonzalez-Calderon/showybox-package#29]
Dear maintainers and developers,

I love `showybox` and I use it for almost my documents. With the last release of Typst and the update of `showybox`, I have found a strange problem related to the interaction of `showybox` and `#set page(margin: xxx)`.

Indeed, using Typst v0.12, the following code : 
```typ
#import "@preview/showybox:2.0.1": *

#set page(margin: 2cm)

#showybox([Hello World!])
```
works as expected, while the same code with the new version `showybox` : 
```typ
#import "@preview/showybox:2.0.2": *

#set page(margin: 2cm)

#showybox([Hello World!])
```
returns the following error : 
```typ
error: unknown variable: margin
    ┌─ @preview/showybox:2.0.2\showy.typ:175:8
    │
175 │         margin.at("y", default: margin.at("top", default: margin.rest))
    │         ^^^^^^
```

This error is a little bit annoying, because it prevents to set custom margin.

Thank you for your help and for developing this package.

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hi!

I think I know how to quick-fix it.

During the day I will make a PR to update the package

**Comment by maucejo** [comment]
Many thanks @Pablo-Gonzalez-Calderon !

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hi!

Changes were submitted as a PR in the Typst Package's repo

I'll mark this as closed now 🫡
