### ISSUE TITLE
use showybox in another function

### ISSUE THREAD

**Issue by oameye** [Pablo-Gonzalez-Calderon/showybox-package#31]
This is a bit of a beginner question but I want to write function in typst that uses showybox to make a note. If I write:
```typst
#let note(title, content) = {
  let box = showybox(
    footer-style: (
      sep-thickness: 0pt,
      align: right,
      color: black
    ),
    title: title,
  )[#content]
  return box
}
#note("Note: ", "This is a note content.")
```
It works if I pass a string, it works. But how do I make it I can pass any content, e.g., math content?

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hi!

You can use squared brackets to pass a `content` to the function. Content is basically any document content you want (check [Typst docs](https://typst.app/docs/reference/foundations/content/) for more info).

Here's two examples of how to use content with your function:

```typst
#note("Note: ", [Hello, this is very cool! #emoji.face.cool])

#note("Note: ")[
  Hello, here's an equation
  $ gradient dot arrow(E) = q/epsilon_0 $
]
```

I hope it helps 🍀

**Comment by oameye** [comment]
Thank you for the help. I am fairly new to typst.
