### ISSUE TITLE
Typo in manual

### ISSUE THREAD

**Issue by WannesMalfait** [Pablo-Gonzalez-Calderon/showybox-package#8]
While reading the manual, I noticed a small grammatical mistake in this part:

3. Parameters
In version 1.0.0. all the parameters that the `showybox()` function can receive are **showed** below:

I think this should be **shown** instead of **showed**.

Couldn't find the source code for the manual in the repo, so just made this issue instead of a PR to let you know.

**Comment by Pablo-Gonzalez-Calderon** [comment]
Yes, It seems I've had a typo 😅. Thank you for taking time reading the manual. I'll change this in v1.1.0 (currently in development)
